# Generated by Django 2.2 on 2019-04-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='lesson name', max_length=150, verbose_name='lesson_name'),
        ),
    ]
